name: Setup
description: Setup Node.js and install dependencies

inputs:
  workingDirectory:
    required: true
    type: string

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: packages/npm/.nvmrc

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.email "contact@trycandle.com"
        git config --global user.name "Candle Finance CI"

    - name: Cache dependencies
      id: yarn-cache
      uses: actions/cache@v3
      with:
        path: |
          ${{ inputs.workingDirectory }}/**/node_modules
          ${{ inputs.workingDirectory }}/.yarn/install-state.gz
        key: ${{ runner.os }}-yarn-${{ inputs.workingDirectory }}-${{ hashFiles('${{ inputs.workingDirectory }}/yarn.lock') }}-${{ hashFiles('${{ inputs.workingDirectory }}/**/package.json', '!**/node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-yarn-${{ inputs.workingDirectory }}-${{ hashFiles('${{ inputs.workingDirectory }}/yarn.lock') }}
          ${{ runner.os }}-yarn-${{ inputs.workingDirectory }}-

    - name: Install dependencies
      run: yarn install --immutable
      working-directory: ${{ inputs.workingDirectory }}
      shell: bash
