name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        workingDirectory: [ "packages/npm/send" ]
    uses: ./.github/workflows/release_shared.yml
    with:
      workingDirectory: ${{ matrix.workingDirectory }}
    secrets: inherit
    name: ${{ matrix.workingDirectory }}
