name: Test

on:
  pull_request:
    branches:
      - main

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        workingDirectory:
          ["packages/npm/prefs", "packages/npm/send", "packages/npm/financekit"]
    uses: ./.github/workflows/tests_shared.yml
    with:
      workingDirectory: ${{ matrix.workingDirectory }}
    secrets: inherit
    name: ${{ matrix.workingDirectory }}
